FROM ubuntu:22.04
WORKDIR /app

RUN apt update && apt install -y \
    build-essential cmake git libhiredis-dev \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN mkdir build && cd build && cmake .. && make

EXPOSE 18080
CMD ["./build/server"]