
services:
  redis:
    image: redis:7-alpine
    container_name: my-redis
    ports:
      - "6379:6379"  
    volumes:
      - redis-data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes  

  
  api:
    build: ./backend
    container_name: redis-api
    ports:
      - "3001:3001"  
    depends_on:
      - redis
    restart: unless-stopped
    environment:
      - NODE_ENV=production

volumes:
  redis-data:  